services:
  docs:
    image: opensearch_filtering_local_docs
    container_name: opensearch_filtering_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./opensearch_filtering:/app/opensearch_filtering:z
    ports:
      - '9000:9000'
    command: /start-docs
