# Generated by Django 5.2.7 on 2025-10-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='opensearch.book'),
        ),
    ]
